const $=id=>document.getElementById(id);let token,templates,endpoints,stimuli=[],matched=[],trial=null,replays={},xReplays=0,annotations=[],currentSid=null;
const status=(x,e=false)=>{$('status').textContent=x;$('status').classList.toggle('error',e)};
async function api(path,payload){const r=await fetch('/api/listening/'+path,{method:'POST',headers:{'Content-Type':'application/json','X-Zaaggenz-Token':token},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
async function renderProject(document,name){const r=await fetch('/api/timeline/render',{method:'POST',headers:{'Content-Type':'application/json','X-Zaaggenz-Token':token},body:JSON.stringify({document,region:null,name})}),j=await r.json();if(!r.ok)throw Error(j.error||'render rejected');for(;;){const q=await fetch(`/api/timeline/jobs/${j.job_id}`),s=await q.json();if(s.state==='completed')return j.job_id;if(s.state==='failed'||s.state==='cancelled')throw Error(s.error||s.state);await new Promise(x=>setTimeout(x,100))}}
function drawStimuli(){$('stimuli').replaceChildren();for(const s of stimuli){const d=document.createElement('div');d.className='stimulus';d.textContent=`${s.name} · ${s.id.slice(0,12)} · ${s.frame_count} frames`;$('stimuli').append(d)}$('create').disabled=stimuli.length<2}
$('materialise').onclick=async()=>{try{for(const f of $('projects').files){status(`Rendering ${f.name}…`);const doc=JSON.parse(await f.text()),job=await renderProject(doc,f.name),s=await api('freeze',{job_id:job,name:f.name,start_frame:0,end_frame:null});stimuli.push(s);drawStimuli()}status(`${stimuli.length} exact examples frozen.`)}catch(e){status(e.message,true)}};
function rowFor(sid){return matched.find(r=>r.stimulus_id===sid)}
function playSid(sid,label){const r=rowFor(sid);if(!r)return;currentSid=sid;replays[sid]=(replays[sid]||0)+1;$('player').src=`/api/listening/audio/${r.playback_sha256}.wav`;$('player').volume=Number($('volume').value)/100;$('player').play().catch(()=>{});status(`Playing ${label}. Replay count ${replays[sid]}.`)}
function drawTrial(){
 $('instructions').textContent=trial.instructions;$('players').replaceChildren();replays=Object.fromEntries(trial.presentation_order.map(x=>[x,0]));xReplays=0;annotations=[];currentSid=null;
 for(const sid of trial.presentation_order){const label=trial.labels[sid],b=document.createElement('button');b.textContent=`Play ${label}`;b.onclick=()=>playSid(sid,label);$('players').append(b)}
 if(trial.design==='abx'){const x=document.createElement('button');x.textContent='Play X';x.onclick=()=>{currentSid=null;xReplays++;$('player').src=`/api/listening/trial/${trial.id}/X.wav`;$('player').volume=Number($('volume').value)/100;$('player').play().catch(()=>{});status('Playing hidden X.')};$('players').append(x)}
 const root=$('response');root.replaceChildren();const choice=document.createElement('select');choice.id='choice';choice.add(new Option('Choose…',''));
 if(trial.design==='abx'){choice.add(new Option('X is A','A'));choice.add(new Option('X is B','B'))}else for(const sid of trial.presentation_order)choice.add(new Option(`Prefer ${trial.labels[sid]}`,sid));const l=document.createElement('label');l.textContent=trial.design==='abx'?'ABX choice':'Comparison choice';l.append(choice);root.append(l);
 for(const ep of trial.endpoints){const d=document.createElement('div');d.className='rating';const label=document.createElement('span');label.textContent=ep.replaceAll('_',' ');const range=document.createElement('input');range.type='range';range.min=0;range.max=100;range.value=50;range.dataset.endpoint=ep;const out=document.createElement('span');out.textContent='50';range.oninput=()=>out.textContent=range.value;d.append(label,range,out);root.append(d)}
 for(const [id,label] of [['confidence','Confidence'],['effort','Effort']]){const d=document.createElement('div');d.className='rating';d.append(Object.assign(document.createElement('span'),{textContent:label}));const r=document.createElement('input');r.type='range';r.min=0;r.max=100;r.value=50;r.id=id;const o=document.createElement('span');o.textContent='50';r.oninput=()=>o.textContent=r.value;d.append(r,o);root.append(d)}
 const ann=document.createElement('button');ann.textContent='Annotate current time';ann.onclick=()=>{const sid=currentSid;if(!sid){status('Annotations on hidden X are not assigned to A/B; play A or B first.',true);return;}annotations.push({stimulus_id:sid,time_seconds:$('player').currentTime,label:'comment',note:''});status(`Annotation added at ${$('player').currentTime.toFixed(2)} s.`)};root.append(ann);$('submit').disabled=false;$('abort').disabled=false;$('export').disabled=false;
}
$('create').onclick=async()=>{try{matched=(await api('match',{stimulus_ids:stimuli.map(s=>s.id),target_rms_dbfs:null,peak_ceiling_dbfs:-3})).matched_stimuli;$('diagnostics').textContent=JSON.stringify(matched,null,2);const eps=[...$('endpoints').selectedOptions].map(o=>o.value);const design=$('design').value;if((design==='ab'||design==='abx')&&matched.length!==2)throw Error(`${design.toUpperCase()} requires exactly two loaded examples.`);trial=(await api('trial',{title:'Listening comparison',design,matched_stimuli:matched,seed:$('seed').value,endpoints:eps.length?eps:['liking','sound_quality'],instruction_template:null})).trial;drawTrial();status(`Trial ${trial.id.slice(0,12)} created. Audio is frozen.`)}catch(e){status(e.message,true)}};
async function submit(kind){if(!trial)return;try{const ratings=Object.fromEntries([...document.querySelectorAll('[data-endpoint]')].map(x=>[x.dataset.endpoint,Number(x.value)])),choice=$('choice').value||null,result={status:kind,choice:kind==='completed'?choice:null,ratings:kind==='completed'?ratings:{},confidence:Number($('confidence')?.value??50),effort:Number($('effort')?.value??50),comfortable_level:Number($('volume').value),replay_counts:replays,x_replay_count:xReplays,annotations,note:''};await api('submit',{trial_id:trial.id,result});status(kind==='completed'?'Result stored.':'Trial marked aborted.');}catch(e){status(e.message,true)}}
$('submit').onclick=()=>submit('completed');$('abort').onclick=()=>submit('aborted');$('stop').onclick=()=>{$('player').pause();$('player').currentTime=0};$('volume').oninput=()=>$('player').volume=Number($('volume').value)/100;
$('rest').onclick=()=>{let n=30;$('rest-state').textContent=`Rest ${n}s`;const id=setInterval(()=>{$('rest-state').textContent=`Rest ${--n}s`;if(n<=0){clearInterval(id);$('rest-state').textContent='Ready'}},1000)};
$('export').onclick=async()=>{try{const b=await api('export',{trial_id:trial.id}),url=URL.createObjectURL(new Blob([JSON.stringify(b,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='zaaggenz-listening-bundle.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){status(e.message,true)}};
const boot=await fetch('/api/listening/bootstrap').then(r=>r.json());token=boot.token;templates=boot.templates;endpoints=boot.endpoints;for(const ep of endpoints)$('endpoints').add(new Option(ep.replaceAll('_',' '),ep,ep==='liking'||ep==='sound_quality',ep==='liking'||ep==='sound_quality'));
