import {VocalEditor,pcm16Wav} from './editor.mjs';
const $=id=>document.getElementById(id);let token,registry,source=null,editor=null,compiled=null,stream=null,ctx=null,node=null,chunks=[];
const status=(s,error=false)=>{$('status').textContent=s;$('status').classList.toggle('error',error);};
async function api(path,payload){const r=await fetch('/api/vocal/'+path,payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Zaaggenz-Token':token},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d;}
async function upload(blob,origin){const r=await fetch('/api/vocal/upload',{method:'POST',headers:{'Content-Type':'audio/wav','X-Capture-Origin':origin,'X-Zaaggenz-Token':token},body:blob});const d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);source=d;$('analyse').disabled=false;$('discard').disabled=false;$('source-audio').src=`/api/vocal/source/${source.source_id}/audio`;compiled=null;editor=null;paint();status(`Loaded ${d.duration_seconds.toFixed(2)} s · ${d.sample_rate_hz} Hz · ${d.channels} channel(s).`);}
function paint(){
  $('segments').replaceChildren();$('compile').disabled=!editor;$('undo').disabled=!editor?.past.length;$('redo').disabled=!editor?.future.length;
  if(!editor)return;const analysis=new Map(editor.document.analysis.segments.map(s=>[s.id,s]));const dictionary=registry.dictionaries.find(d=>d.id===editor.document.dictionary_id),tokens=dictionary.entries.map(e=>e.token);
  for(const row of editor.document.segments){const a=analysis.get(row.segment_id),div=document.createElement('div');div.className='segment';div.dataset.id=row.segment_id;
    const check=document.createElement('label');check.textContent='Use';const approved=document.createElement('input');approved.type='checkbox';approved.checked=row.approved;check.append(approved);div.append(check);
    const metric=document.createElement('div');metric.className='metric';metric.textContent=`${a.voicing}\npitch conf ${(a.pitch_confidence*100).toFixed(0)}%\nbright conf ${(a.brightness_confidence*100).toFixed(0)}%`;div.append(metric);
    const mk=(label,el)=>{const l=document.createElement('label');l.textContent=label;l.append(el);div.append(l);return el;};
    const tok=document.createElement('select');for(const t of tokens)tok.add(new Option(t,t));tok.value=row.token;mk('Mnemonic',tok);
    const beat=document.createElement('input');beat.value=row.aligned_beat;mk('Aligned beat',beat);
    const offset=document.createElement('input');offset.type='number';offset.value=row.manual_offset_samples;mk(`Offset samples\n(orig err ${row.alignment_error_samples})`,offset);
    const mode=document.createElement('select');for(const x of ['estimate','manual','unpitched'])mode.add(new Option(x,x));mode.value=row.pitch_mode;mk('Pitch mode',mode);
    const pitch=document.createElement('input');pitch.type='number';pitch.step='any';pitch.placeholder=a.pitch_hz?.toFixed(2)??'unpitched';pitch.value=row.manual_pitch_hz??'';mk('Manual pitch Hz',pitch);
    const bright=document.createElement('input');bright.type='number';bright.step='any';bright.placeholder=a.brightness_hz?.toFixed(1)??'unknown';bright.value=row.manual_brightness_hz??'';mk('Brightness Hz',bright);
    const onset=document.createElement('div');onset.className='metric';onset.textContent=`samples ${a.start_sample}–${a.end_sample}\naccent ${a.accent_db.toFixed(1)} dB`;div.append(onset);
    const update=()=>{try{const changes={approved:approved.checked,token:tok.value,aligned_beat:beat.value,manual_offset_samples:Number(offset.value),pitch_mode:mode.value,manual_pitch_hz:pitch.value===''?null:Number(pitch.value),manual_brightness_hz:bright.value===''?null:Number(bright.value)};editor.patch(row.segment_id,changes);compiled=null;paint();status('Correction changed. Update preview before applying.');}catch(e){status(e.message,true);}};
    for(const el of [approved,tok,beat,offset,mode,pitch,bright])el.addEventListener('change',update);$('segments').append(div);
  }
}
async function compile(){if(!editor)return;try{compiled=await api('compile',{edit:editor.document});$('preview').textContent=JSON.stringify({revision:compiled.timeline_revision_id,source_disposition:compiled.preview.source_disposition,events:compiled.preview.events,automation:compiled.automation},null,2);$('render').disabled=false;$('apply').disabled=false;status(`Preview ready · ${compiled.preview.events.length} approved regions · revision ${compiled.timeline_revision_id.slice(0,12)}.`);}catch(e){compiled=null;$('render').disabled=true;$('apply').disabled=true;status(e.message,true);}}
async function analyze(){try{const d=await api('analyse',{source_id:source.source_id,dictionary_id:$('dictionary').value,grid_beats:$('grid').value});editor=new VocalEditor(d.edit);compiled=d;paint();$('preview').textContent=JSON.stringify(d.preview,null,2);$('render').disabled=false;$('apply').disabled=false;status(`Analysis: ${d.analysis.diagnostics.voiced_segments} voiced, ${d.analysis.diagnostics.unvoiced_segments} unvoiced, ${d.analysis.diagnostics.low_confidence_segments} low-confidence. Original timing retained.`);}catch(e){status(e.message,true);}}
$('file').addEventListener('change',async()=>{const f=$('file').files[0];if(f)try{await upload(f,'local-import');}catch(e){status(e.message,true);}finally{$('file').value='';}});
$('record').onclick=async()=>{try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Recording input is unavailable in this browser; WAV import remains available.');stream=await navigator.mediaDevices.getUserMedia({audio:true});ctx=new AudioContext();const src=ctx.createMediaStreamSource(stream);node=ctx.createScriptProcessor(4096,1,1);chunks=[];node.onaudioprocess=e=>chunks.push(new Float32Array(e.inputBuffer.getChannelData(0)));src.connect(node);node.connect(ctx.destination);$('record').disabled=true;$('stop-record').disabled=false;$('record-state').textContent='Recording locally in this loopback session.';}catch(e){$('record-state').textContent=e.message;}};
$('stop-record').onclick=async()=>{try{node?.disconnect();stream?.getTracks().forEach(t=>t.stop());const rate=ctx.sampleRate;await ctx.close();$('record').disabled=false;$('stop-record').disabled=true;await upload(pcm16Wav(chunks,rate),'local-recording');$('record-state').textContent='Recording loaded into local session.';}catch(e){status(e.message,true);}};
$('analyse').onclick=analyze;$('compile').onclick=compile;
$('undo').onclick=()=>{if(editor?.undo()){compiled=null;paint();status('Correction undone. Update preview.');}};$('redo').onclick=()=>{if(editor?.redo()){compiled=null;paint();status('Correction redone. Update preview.');}};
$('discard').onclick=async()=>{if(!source||!editor)return;try{const d=await api('discard',{source_id:source.source_id,edit:editor.document});editor.replace(d.edit,{resetHistory:true});$('source-audio').removeAttribute('src');$('source-audio').load();$('discard').disabled=true;$('analyse').disabled=true;compiled=null;paint();await compile();status('Raw source discarded from the local session. Derived corrections and compiled gesture remain usable.');}catch(e){status(e.message,true);}};
$('apply').onclick=()=>{if(!compiled)return;const blob=new Blob([JSON.stringify(compiled.timeline,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='zaaggenz-vocal-capture.zgtimeline.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('render').onclick=async()=>{if(!compiled)return;try{const r=await fetch('/api/timeline/render',{method:'POST',headers:{'Content-Type':'application/json','X-Zaaggenz-Token':token},body:JSON.stringify({document:compiled.timeline,region:null,name:'Vocal capture preview'})}),job=await r.json();if(!r.ok)throw Error(job.error||'render rejected');for(;;){const q=await fetch(`/api/timeline/jobs/${job.job_id}`),s=await q.json();if(s.state==='completed')break;if(s.state==='failed'||s.state==='cancelled')throw Error(s.error||s.state);await new Promise(x=>setTimeout(x,100));}$('render-audio').src=`/api/timeline/jobs/${job.job_id}/audio`;await $('render-audio').play().catch(()=>{});status('Source-derived preview rendered.');}catch(e){status(e.message,true);}};
const boot=await api('bootstrap');token=boot.token;registry=boot.registry;for(const d of registry.dictionaries)$('dictionary').add(new Option(d.id,d.id));$('record-state').textContent='Idle. Recording has not been requested.';
