from __future__ import annotations
from dataclasses import dataclass
from fractions import Fraction
import math,re
from .core import Tuning,KeyboardMap,TuningError,cents_to_ratio,ratio_to_cents

MAX_TEXT=1_000_000

@dataclass(frozen=True)
class ScalaScale:
    description:str
    pitch_ratios:tuple[float,...]  # file pitches, final item is the period
    def __post_init__(self):
        if not 1<=len(self.pitch_ratios)<=256:raise TuningError('Scala scale requires 1..256 pitches including period')
        values=tuple(float(v) for v in self.pitch_ratios)
        if any(not math.isfinite(v) or v<=0 for v in values):raise TuningError('Scala pitch ratios must be positive')
        if any(a>=b for a,b in zip(values,values[1:])):raise TuningError('Scala pitches must be strictly increasing')
        if values[-1]<=1:raise TuningError('Scala period must be greater than unison')
    @property
    def period_ratio(self):return self.pitch_ratios[-1]
    @property
    def degree_ratios(self):return (1.0,*self.pitch_ratios[:-1])

@dataclass(frozen=True)
class ScalaKBM:
    map_size:int;first_key:int;last_key:int;middle_key:int;reference_key:int;reference_hz:float;formal_period_degrees:int;entries:tuple[int|None,...]
    def __post_init__(self):
        if not 0<=self.map_size<=128:raise TuningError('KBM map size out of range')
        if not 0<=self.first_key<=self.last_key<=127 or not 0<=self.middle_key<=127 or not 0<=self.reference_key<=127:raise TuningError('KBM key out of MIDI range')
        if not math.isfinite(self.reference_hz) or self.reference_hz<=0:raise TuningError('KBM reference Hz invalid')
        if self.map_size==0 and self.entries:raise TuningError('zero-size KBM cannot contain entries')
        if self.map_size and len(self.entries)!=self.map_size:raise TuningError('KBM entry count mismatch')
        for x in self.entries:
            if x is not None and (type(x)is not int or not -4096<=x<=4096):raise TuningError('KBM map degree invalid')
    def expanded_entries(self):
        if self.map_size:return self.entries
        if not 1<=self.formal_period_degrees<=128:raise TuningError('zero-size KBM needs formal period 1..128 for explicit contract mapping')
        return tuple(range(self.formal_period_degrees))
    def degree(self,key):
        entries=self.expanded_entries();m=len(entries)
        if not self.first_key<=key<=self.last_key:return None
        q,r=divmod(key-self.middle_key,m);x=entries[r]
        return None if x is None else q*self.formal_period_degrees+x
    def to_keyboard_map(self):
        entries=self.expanded_entries()
        return KeyboardMap(self.first_key,self.last_key,self.middle_key,self.reference_key,self.formal_period_degrees,entries)

def _text(value):
    if isinstance(value,bytes):
        try:value=value.decode('utf-8-sig')
        except UnicodeError as e:raise TuningError('Scala file must be UTF-8') from e
    if not isinstance(value,str) or len(value.encode('utf-8'))>MAX_TEXT:raise TuningError('Scala text missing or too large')
    return value.replace('\r\n','\n').replace('\r','\n')

def _noncomment_lines(text,preserve_blank=True):
    out=[]
    for raw in _text(text).split('\n'):
        if raw.lstrip().startswith('!'):continue
        out.append(raw.strip())
    return out

def _pitch(token):
    token=token.strip()
    if not token:raise TuningError('empty Scala pitch')
    try:
        if '.' in token or 'e' in token.lower(): ratio=cents_to_ratio(float(token))
        elif '/' in token: ratio=float(Fraction(token))
        else: ratio=float(int(token))
    except (ValueError,ZeroDivisionError,OverflowError) as e:raise TuningError('invalid Scala pitch: '+token) from e
    if not math.isfinite(ratio) or ratio<=0:raise TuningError('Scala pitch ratio must be positive')
    return ratio

def parse_scl(text):
    lines=_noncomment_lines(text)
    if not lines:raise TuningError('empty SCL')
    description=lines[0]
    i=1
    while i<len(lines) and not lines[i]:i+=1
    if i>=len(lines):raise TuningError('SCL note count missing')
    try:count=int(lines[i])
    except ValueError as e:raise TuningError('invalid SCL note count') from e
    if not 1<=count<=256:raise TuningError('SCL note count must be 1..256 for a playable tuning')
    tokens=[]
    for line in lines[i+1:]:
        if not line:continue
        token=line.split('!',1)[0].split()[0] if line.split('!',1)[0].split() else ''
        if token:tokens.append(token)
    if len(tokens)!=count:raise TuningError(f'SCL declares {count} pitches but contains {len(tokens)}')
    return ScalaScale(description,tuple(_pitch(t) for t in tokens))

def export_scl(scale):
    if not isinstance(scale,ScalaScale):raise TuningError('ScalaScale required')
    desc=scale.description.replace('\n',' ').replace('\r',' ').replace('!','').strip()
    lines=['! generated by zaaggenz tuning v1',desc,str(len(scale.pitch_ratios))]
    for ratio in scale.pitch_ratios:lines.append(f'{ratio_to_cents(ratio):.12f}')
    return '\n'.join(lines)+'\n'

def _kbm_data_lines(text):
    out=[]
    for raw in _text(text).split('\n'):
        clean=raw.split('!',1)[0].strip()
        if clean:out.append(clean)
    return out

def parse_kbm(text):
    lines=_kbm_data_lines(text)
    if len(lines)<7:raise TuningError('KBM requires seven header fields')
    try:
        size=int(lines[0]);first=int(lines[1]);last=int(lines[2]);middle=int(lines[3]);ref=int(lines[4]);hz=float(lines[5]);formal=int(lines[6])
    except ValueError as e:raise TuningError('invalid KBM header') from e
    if not 0<=size<=128:raise TuningError('KBM map size must be 0..128')
    raw=lines[7:]
    if len(raw)!=size:raise TuningError(f'KBM declares {size} map entries but contains {len(raw)}')
    entries=[]
    for x in raw:
        if x.lower()=='x':entries.append(None)
        else:
            try:entries.append(int(x))
            except ValueError as e:raise TuningError('invalid KBM map entry') from e
    return ScalaKBM(size,first,last,middle,ref,hz,formal,tuple(entries))

def export_kbm(kbm):
    if not isinstance(kbm,ScalaKBM):raise TuningError('ScalaKBM required')
    lines=['! generated by zaaggenz tuning v1',str(kbm.map_size),str(kbm.first_key),str(kbm.last_key),str(kbm.middle_key),str(kbm.reference_key),f'{kbm.reference_hz:.17g}',str(kbm.formal_period_degrees)]
    lines.extend('x' if x is None else str(x) for x in kbm.entries)
    return '\n'.join(lines)+'\n'

def load_scala_tuning(scl_text,kbm_text=None,*,tuning_id='scala-import'):
    scale=parse_scl(scl_text)
    if kbm_text is None:
        count=len(scale.degree_ratios);middle=60;ref=69
        # default linear keyboard mapping, A4 reference; degree is explicit and portable.
        keyboard=KeyboardMap(0,127,middle,ref,count,tuple(range(count)))
        reference_degree=keyboard.degree(ref);reference_hz=440.0
    else:
        raw=parse_kbm(kbm_text);keyboard=raw.to_keyboard_map();reference_degree=keyboard.degree(raw.reference_key);reference_hz=raw.reference_hz
        if reference_degree is None:raise TuningError('KBM reference key is unmapped')
    return Tuning(tuning_id,reference_hz,reference_degree,scale.period_ratio,tuple(scale.degree_ratios),keyboard,scale.description,'scala')
