const $=id=>document.getElementById(id);let token='',state=null,activeSlot='A',pollTimer=null;
const ns='http://www.w3.org/2000/svg';
function el(name,attrs={}){const x=document.createElementNS(ns,name);for(const [k,v] of Object.entries(attrs))x.setAttribute(k,String(v));return x}
function controls(){return {amount:Number($('amount').value),root_hz:Number($('root-hz').value),sonority:$('sonority').value,anchor:$('anchor').value}}
async function api(path,opts={}){const r=await fetch(path,{cache:'no-store',...opts,headers:{...(opts.headers||{}),'X-Zaaggenz-Token':token}});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{throw new Error(text||r.statusText)}if(!r.ok)throw new Error(data.error||data.message||text||r.statusText);return data}
async function post(path,payload){return api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})}
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error)}
function hz(v){return v==null?'—':`${Number(v).toFixed(1)} Hz`}
function short(v){return v?String(v).slice(0,12):'—'}
function setAudio(slot,{preserve=true}={}){const audio=$('audio');const old=preserve&&Number.isFinite(audio.currentTime)?audio.currentTime:0;activeSlot=slot;$('slot-a').classList.toggle('active',slot==='A');$('slot-b').classList.toggle('active',slot==='B');$('slot-a').setAttribute('aria-pressed',slot==='A');$('slot-b').setAttribute('aria-pressed',slot==='B');const compensated=slot==='B'&&$('compensate').checked;const rev=state?.slots?.[slot]?.revision_id||'';audio.src=`/api/inspector/audio/${slot}?compensated=${compensated?1:0}&v=${encodeURIComponent(rev)}`;audio.load();audio.addEventListener('loadedmetadata',()=>{if(old>0&&Number.isFinite(audio.duration))audio.currentTime=Math.min(old,Math.max(0,audio.duration-.001));}, {once:true});}
function yMap(freq,min,max){const lo=Math.log(Math.max(min,1)),hi=Math.log(Math.max(max,min+1));return 405-(Math.log(Math.max(freq,min))-lo)/(hi-lo)*360}
function xWindow(snapshot){const frames=snapshot.before.frame_count,sr=snapshot.before.sample_rate_hz,total=frames/sr,zoom=Number($('zoom').value),span=total/zoom,center=Number.isFinite($('audio').currentTime)?$('audio').currentTime:total/2;let start=Math.max(0,Math.min(total-span,center-span/2));return {start,end:start+span,total}}
function drawTimeline(){if(!state)return;const snap=state.snapshot,svg=$('timeline');svg.replaceChildren();const threshold=Number($('confidence').value),win=xWindow(snap);svg.dataset.zoom=String($('zoom').value);let maxHz=500,minHz=70;for(const c of snap.components){maxHz=Math.max(maxHz,c.estimated_hz,c.realised_hz,c.requested_hz||0)}for(const comb of snap.target_combs)for(const f of comb.teeth_hz)maxHz=Math.max(maxHz,f);maxHz*=1.08;
 for(let i=0;i<=10;i++){svg.append(el('line',{x1:40,y1:405-i*36,x2:985,y2:405-i*36,class:'grid'}))}
 const x=t=>40+(t-win.start)/(win.end-win.start)*945;
 for(const comb of snap.target_combs){if(!comb.selected)continue;for(const f of comb.teeth_hz){if(f<minHz||f>maxHz)continue;const line=el('line',{x1:40,y1:yMap(f,minHz,maxHz),x2:985,y2:yMap(f,minHz,maxHz),class:'comb'});const title=el('title');title.textContent=`${comb.label} target ${f.toFixed(1)} Hz`;line.append(title);svg.append(line)}}
 let masked=0,shown=[];
 for(const c of snap.components){if(c.time_seconds<win.start||c.time_seconds>win.end)continue;const xx=x(c.time_seconds),ye=yMap(c.estimated_hz,minHz,maxHz),yr=yMap(c.realised_hz,minHz,maxHz);const maskedNow=c.confidence<threshold;if(maskedNow)masked++;const line=el('line',{x1:xx,y1:ye,x2:xx,y2:yr,class:'trajectory'});svg.append(line);if(c.requested_hz){const req=el('rect',{x:xx-3,y:yMap(c.requested_hz,minHz,maxHz)-3,width:6,height:6,fill:'none',stroke:'var(--amber)','stroke-width':1.2});svg.append(req)}const circle=el('circle',{cx:xx,cy:yr,r:4.2,class:`component ${c.classification}${maskedNow?' masked':''}`});circle.dataset.confidence=String(c.confidence);circle.dataset.masked=maskedNow?'1':'0';const title=el('title');title.textContent=`${c.track_id} · requested ${hz(c.requested_hz)} · estimated ${hz(c.estimated_hz)} · realised ${hz(c.realised_hz)} · conf ${c.confidence.toFixed(2)} · ${c.reason}`;circle.append(title);svg.append(circle);shown.push(c)}
 $('masked-count').textContent=`${masked} masked`;$('pitch-table').replaceChildren(...shown.slice(0,14).map(c=>{const tr=document.createElement('tr');for(const v of [c.track_id,hz(c.requested_hz),hz(c.estimated_hz),hz(c.realised_hz),c.confidence.toFixed(2)]){const td=document.createElement('td');td.textContent=v;tr.append(td)}return tr}));}
function drawLine(svgId,rows,xKey,yKey,cls,xRange=null){const svg=$(svgId);svg.replaceChildren();if(!rows.length)return;const xs=rows.map(r=>Number(r[xKey])).filter(Number.isFinite),ys=rows.map(r=>Number(r[yKey])).filter(Number.isFinite);if(!xs.length||!ys.length)return;const xmin=xRange?.[0]??Math.min(...xs),xmax=xRange?.[1]??Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);const px=x=>40+(x-xmin)/Math.max(1e-12,xmax-xmin)*945,py=y=>155-(y-ymin)/Math.max(1e-12,ymax-ymin)*125;for(let i=0;i<6;i++)svg.append(el('line',{x1:40,y1:155-i*25,x2:985,y2:155-i*25,class:'grid'}));const points=rows.filter(r=>Number.isFinite(Number(r[yKey]))).map(r=>`${px(Number(r[xKey]))},${py(Number(r[yKey]))}`).join(' ');svg.append(el('polyline',{points,class:cls}));}
function renderState(next){state=next;const snap=state.snapshot;$('snapshot-id').textContent=short(snap.snapshot_id);$('source-revision').textContent=short(state.slots.A.revision_id);$('after-revision').textContent=short(state.slots.B.revision_id);$('working-revision').textContent=short(state.working.revision_id);$('undo-depth').textContent=String(state.undo_depth);$('stage-order').textContent=snap.stage_order.join(' → ');$('compensation').textContent=`B compensation ${state.compensation.gain_db.toFixed(2)} dB${state.compensation.peak_limited?' · peak limited':''}`;const counts=snap.uncertainty.counts;$('moved-count').textContent=counts.moved;$('unaffected-count').textContent=counts.unaffected;$('uncertain-count').textContent=counts.uncertain;$('stale-warning').classList.toggle('hidden',!state.snapshot_stale);$('apply').disabled=state.snapshot_stale;$('freeze').disabled=state.snapshot_stale;$('undo').disabled=state.undo_depth===0;$('expert').textContent=JSON.stringify({method:snap.method,controls:snap.controls,diagnostics:snap.diagnostics,expert:snap.expert,policy:state.policy},null,2);$('confidence').value=String(snap.uncertainty.confidence_threshold);$('confidence-value').textContent=Number($('confidence').value).toFixed(2);drawTimeline();drawLine('remainder',snap.remainder,'time_seconds','rms_dbfs','remainder-line');drawLine('compatibility',snap.compatibility.filter(r=>r.value!=null),'interval_cents','value','compat-line',[0,1200]);setAudio(activeSlot,{preserve:true});}
async function refresh(){renderState(await api('/api/inspector/state'))}
async function analyse(){try{$('analyse').disabled=true;status('Analysis pending · current sound remains unchanged');const job=await post('/api/inspector/analyse',{controls:controls()});const poll=async()=>{try{const s=await api(`/api/inspector/jobs/${job.job_id}`);if(s.state==='completed'){if(s.stale){await refresh();status('Stale analysis rejected: slot A changed before completion.',true)}else{renderState(s.state_payload);status('Analysis published to inspector only · click Apply explicitly to change working sound.')} $('analyse').disabled=false;return}if(s.state==='failed'||s.state==='cancelled'){status(`Analysis ${s.state}`,true);$('analyse').disabled=false;return}pollTimer=setTimeout(poll,80)}catch(e){status(e.message,true);$('analyse').disabled=false;}};poll()}catch(e){status(e.message,true);$('analyse').disabled=false}}
async function action(path,payload,msg){try{await post(path,payload);await refresh();status(msg)}catch(e){status(e.message,true)}}
$('amount').addEventListener('input',()=>{$('amount-value').textContent=Number($('amount').value).toFixed(2)});$('confidence').addEventListener('input',()=>{$('confidence-value').textContent=Number($('confidence').value).toFixed(2);drawTimeline()});$('zoom').addEventListener('input',drawTimeline);$('analyse').addEventListener('click',analyse);$('freeze').addEventListener('click',()=>action('/api/inspector/freeze',{snapshot_id:state.snapshot.snapshot_id},'Snapshot frozen; later analysis cannot replace this frozen reference.'));$('apply').addEventListener('click',()=>action('/api/inspector/apply',{snapshot_id:state.snapshot.snapshot_id},'Transform applied explicitly to working state.'));$('undo').addEventListener('click',()=>action('/api/inspector/undo',{},'Apply undone; previous working state restored.'));$('slot-a').addEventListener('click',()=>setAudio('A'));$('slot-b').addEventListener('click',()=>setAudio('B'));$('compensate').addEventListener('change',()=>{if(activeSlot==='B')setAudio('B')});$('scrub').addEventListener('input',()=>{const a=$('audio');if(Number.isFinite(a.duration))a.currentTime=Number($('scrub').value)*a.duration});$('audio').addEventListener('timeupdate',()=>{const a=$('audio');if(Number.isFinite(a.duration)&&a.duration>0){$('scrub').value=String(a.currentTime/a.duration);$('transport-time').textContent=`${a.currentTime.toFixed(3)} s`;drawTimeline()}});
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.key==='1'){e.preventDefault();setAudio('A')}else if(e.key==='2'){e.preventDefault();setAudio('B')}else if(e.key===' '){e.preventDefault();const a=$('audio');a.paused?a.play():a.pause()}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const a=$('audio');a.currentTime=Math.max(0,Math.min(a.duration||0,a.currentTime+(e.key==='ArrowRight'?1:-1)))}});
(async()=>{try{const boot=await fetch('/api/inspector/bootstrap',{cache:'no-store'}).then(r=>r.json());token=boot.token;renderState(boot.state);status('Ready · analysis is non-destructive until Apply explicitly.')}catch(e){status(e.message,true)}})();
